module Hephaestux.Agents
  ( AgentSpec (..),
    allAgents,
    lookupAgent,
    agentNames,
  )
where

import Data.Text (Text)
import qualified Data.Text as Text
import Hephaestux.Install (InstallStep (..))

data AgentSpec = AgentSpec
  { specName :: Text,
    symbol :: Text,
    procNames :: [Text],
    plan :: [InstallStep],
    notes :: [Text]
  }

-- | Registry of the 10 supported agents.
allAgents :: [AgentSpec]
allAgents =
  [ ompSpec,
    piSpec,
    claudeSpec,
    codexSpec,
    opencodeSpec,
    antigravitySpec,
    kimiSpec,
    qwenSpec,
    clineSpec,
    deepseekSpec
  ]

lookupAgent :: Text -> Maybe AgentSpec
lookupAgent n = case filter ((== n) . (.specName)) allAgents of
  (a : _) -> Just a
  [] -> Nothing

agentNames :: [Text]
agentNames = map (.specName) allAgents

-- | Shared TS hook factory body for omp and pi (same extension API).
ompSpec :: AgentSpec
ompSpec =
  AgentSpec
    { specName = "omp",
      symbol = "Ω",
      procNames = ["omp"],
      plan = [WriteFile "~/.omp/agent/hooks/post/hephaestux.ts" (tsFactory "omp" "Ω")],
      notes = []
    }

piSpec :: AgentSpec
piSpec =
  AgentSpec
    { specName = "pi",
      symbol = "π",
      procNames = ["pi"],
      plan = [WriteFile "~/.pi/agent/extensions/hephaestux.ts" (tsFactory "pi" "π")],
      notes = []
    }

-- | Shared TS hook factory body for omp and pi (same extension API).
tsFactory :: Text -> Text -> Text
tsFactory agent sym =
  "// Generated by hephaestux setup; safe to regenerate.\n\
  \export default function (pi: any) {\n\
  \  const call = async (state: string, title: string | undefined) => {\n\
  \    const args = [\"update\", \"--agent\", \""
    <> agent
    <> "\", \"--symbol\", \""
    <> sym
    <> "\", \"--state\", state];\n\
       \    if (title) args.push(\"--title\", title);\n\
       \    try {\n\
       \      await pi.exec(\"hephaestux\", args);\n\
       \    } catch {\n\
       \      // never break the agent\n\
       \    }\n\
       \  };\n\
       \  pi.on(\"session_start\", () => { void call(\"stale\", undefined); });\n\
       \  pi.on(\"agent_start\", () => { void call(\"working\", undefined); });\n\
       \  pi.on(\"agent_end\", () => { void call(\"waiting-input\", undefined); });\n\
       \  pi.on(\"session_shutdown\", () => {\n\
       \    try {\n\
       \      void pi.exec(\"hephaestux\", [\"end\"]);\n\
       \    } catch {\n\
       \      // never break the agent\n\
       \    }\n\
       \  });\n\
       \}\n"

claudeSpec :: AgentSpec
claudeSpec =
  AgentSpec
    { specName = "claude",
      symbol = "Cl",
      procNames = ["claude"],
      plan = [MergeJsonHooks "~/.claude/settings.json" (claudeHooks "claude" "Cl")],
      notes = []
    }

codexSpec :: AgentSpec
codexSpec =
  AgentSpec
    { specName = "codex",
      symbol = "Cx",
      procNames = ["codex"],
      plan = [MergeJsonHooks "~/.codex/hooks.json" (claudeHooks "codex" "Cx")],
      notes =
        [ "run /hooks in codex to trust the new hooks"
        ]
    }

-- | Claude-shape hooks config: an OBJECT keyed by event (official schema):
-- SessionStart -> stale, UserPromptSubmit -> working, Stop -> waiting-input,
-- SessionEnd -> end (timeout 3 on codex).
claudeHooks :: Text -> Text -> Text
claudeHooks agent sym =
  "{\n"
    <> updateEntry agent sym "stale"
    <> updateEntry agent sym "working"
    <> updateEntry agent sym "waiting-input"
    <> endEntry (Just 3)
    <> "}\n"

updateEntry :: Text -> Text -> Text -> Text
updateEntry agent sym state =
  "  \""
    <> eventFor state
    <> "\": [{ \"hooks\": [{ \"type\": \"command\", \"command\": \"hephaestux update --agent "
    <> agent
    <> " --symbol "
    <> sym
    <> " --state "
    <> state
    <> " || true\" }]}],\n"

eventFor :: Text -> Text
eventFor = \case
  "stale" -> "SessionStart"
  "working" -> "UserPromptSubmit"
  "waiting-input" -> "Stop"
  _ -> "SessionEnd"

endEntry :: Maybe Int -> Text
endEntry mtimeout =
  "  \"SessionEnd\": [{ \"hooks\": [{ \"type\": \"command\", \"command\": \"hephaestux end || true\""
    <> maybe "" (\t -> ", \"timeout\": " <> Text.pack (show t)) mtimeout
    <> " }]}]\n"

opencodeSpec :: AgentSpec
opencodeSpec =
  AgentSpec
    { specName = "opencode",
      symbol = "Oc",
      procNames = ["opencode"],
      plan = [WriteFile "~/.config/opencode/plugins/hephaestux.ts" opencodePlugin],
      notes = []
    }

opencodePlugin :: Text
opencodePlugin =
  "// Generated by hephaestux setup; safe to regenerate.\n\
  \import type { Plugin } from \"@opencode-ai/plugin\";\n\
  \\n\
  \const update = async (state: string) => {\n\
  \  try {\n\
  \    const proc = Bun.spawn([\"hephaestux\", \"update\", \"--agent\", \"opencode\", \"--symbol\", \"Oc\", \"--state\", state], { stdout: \"ignore\", stderr: \"ignore\" });\n\
  \    await proc.exited;\n\
  \  } catch {\n\
  \    // never break the agent\n\
  \  }\n\
  \};\n\
  \\n\
  \export const HephaestuxPlugin: Plugin = async () => ({\n\
  \  event: async ({ event }) => {\n\
  \    if (event.type === \"session.created\") await update(\"stale\");\n\
  \    if (event.type === \"chat.message\") await update(\"working\");\n\
  \    if (event.type === \"session.idle\") await update(\"waiting-input\");\n\
  \    if (event.type === \"session.deleted\") {\n\
  \      try {\n\
  \        const proc = Bun.spawn([\"hephaestux\", \"end\"], { stdout: \"ignore\", stderr: \"ignore\" });\n\
  \        await proc.exited;\n\
  \      } catch {\n\
  \        // never break the agent\n\
  \      }\n\
  \    }\n\
  \  },\n\
  \});\n\
  \\n\
  \export default HephaestuxPlugin;\n"

antigravitySpec :: AgentSpec
antigravitySpec =
  AgentSpec
    { specName = "antigravity",
      symbol = "Ag",
      procNames = ["antigravity", "gemini"],
      plan = [ReplaceJsonKey "~/.gemini/config/hooks.json" antigravityHooks],
      notes =
        [ "no SessionStart event exists: no stale state is emitted"
        ]
    }

antigravityHooks :: Text
antigravityHooks =
  "{\n\
  \  \"PreInvocation\": [{ \"type\": \"command\", \"command\": \"hephaestux update --agent antigravity --symbol Ag --state working || true\" }],\n\
  \  \"Stop\": [{ \"type\": \"command\", \"command\": \"hephaestux update --agent antigravity --symbol Ag --state waiting-input || true; echo '{\\\"decision\\\":\\\"noop\\\"}'\" }]\n\
  \}\n"

kimiSpec :: AgentSpec
kimiSpec =
  AgentSpec
    { specName = "kimi",
      symbol = "Ki",
      procNames = ["kimi"],
      plan = [AppendTomlHooks "~/.kimi/config.toml" kimiToml],
      notes = []
    }

kimiToml :: Text
kimiToml =
  "\n\
  \[[hooks]]\n\
  \event = \"SessionStart\"\n\
  \command = \"hephaestux update --agent kimi --symbol Ki --state stale || true\"\n\
  \\n\
  \[[hooks]]\n\
  \event = \"UserPromptSubmit\"\n\
  \command = \"hephaestux update --agent kimi --symbol Ki --state working || true\"\n\
  \\n\
  \[[hooks]]\n\
  \event = \"Stop\"\n\
  \command = \"hephaestux update --agent kimi --symbol Ki --state waiting-input || true\"\n\
  \\n\
  \[[hooks]]\n\
  \event = \"SessionEnd\"\n\
  \command = \"hephaestux end || true\"\n\
  \"

qwenSpec :: AgentSpec
qwenSpec =
  AgentSpec
    { specName = "qwen",
      symbol = "Qw",
      procNames = ["qwen"],
      plan = [MergeJsonHooks "~/.qwen/settings.json" (claudeHooks "qwen" "Qw")],
      notes = []
    }

clineSpec :: AgentSpec
clineSpec =
  AgentSpec
    { specName = "cline",
      symbol = "Cn",
      procNames = ["cline"],
      plan =
        [ WriteFile ".cline/hooks/TaskStart" (clineHook "cline" "Cn" "stale"),
          WriteFile ".cline/hooks/TaskResume" (clineHook "cline" "Cn" "working"),
          WriteFile ".cline/hooks/UserPromptSubmit" (clineHook "cline" "Cn" "working"),
          WriteFile ".cline/hooks/TaskCancel" "#!/bin/sh\nhephaestux end || true\n",
          MakeExecutable ".cline/hooks/TaskStart",
          MakeExecutable ".cline/hooks/TaskResume",
          MakeExecutable ".cline/hooks/UserPromptSubmit",
          MakeExecutable ".cline/hooks/TaskCancel"
        ],
      notes =
        [ "no idle event exists: no waiting-input signal",
          "hooks are installed in the current working directory"
        ]
    }

clineHook :: Text -> Text -> Text -> Text
clineHook agent sym state =
  "#!/bin/sh\nhephaestux update --agent " <> agent <> " --symbol " <> sym <> " --state " <> state <> " || true\n"

deepseekSpec :: AgentSpec
deepseekSpec =
  AgentSpec
    { specName = "deepseek",
      symbol = "Ds",
      procNames = ["deepseek", "dsh"],
      plan =
        [ WriteFile ".hephaestux/dsh-hooks.json" (claudeHooksNoEnd "deepseek" "Ds"),
          WriteFile "cordis-hephaestux.yml" deepseekOverlay
        ],
      notes =
        [ "launch with: dsh web --patch cordis-hephaestux.yml",
          "no SessionEnd event: dead-pid filtering covers cleanup",
          "hooks are installed in the current working directory"
        ]
    }

-- | Claude-shape hooks without SessionEnd (deepseek has no such event).
claudeHooksNoEnd :: Text -> Text -> Text
claudeHooksNoEnd agent sym =
  "{\n"
    <> updateEntry agent sym "stale"
    <> updateEntry agent sym "working"
    <> "  \"Stop\": [{ \"hooks\": [{ \"type\": \"command\", \"command\": \"hephaestux update --agent "
    <> agent
    <> " --symbol "
    <> sym
    <> " --state waiting-input || true\" }]}]\n\
       \}\n"

deepseekOverlay :: Text
deepseekOverlay =
  "# Generated by hephaestux setup.\n\
  \hooks:\n\
  \  provider: \"@deepseek-ai/dsh-hooks-claude-code\"\n\
  \  configPath: \".hephaestux/dsh-hooks.json\"\n"
